#!/bin/sh

sed -i "s/django-secret-key/`pwgen -1 -s 48`/" /opt/sci-web/sci_webinterface/settings.py

if [ -e /var/lib/ganeti/rapi/users ]; then
	sed -i "s/scpassword/`cat /var/lib/ganeti/rapi/users|grep scweb|awk '{print $2}'`/" /opt/sci-web/sci_webinterface/settings.py
fi

if [ -e /etc/ganeti/vnc-cluster-password ]; then
	sed -i "s/vncpassword/`cat /etc/ganeti/vnc-cluster-password`/" /opt/sci-web/sci_webinterface/settings.py
fi

if [ ! -e /stuff/cdimages ]; then
	mkdir -p /stuff/cdimages
fi

(cd /opt/sci-web; python3 ./manage.py makemigrations hosts; python3 ./manage.py migrate; python3 ./manage.py migrate --database=tasks --run-syncdb; python3 ./manage.py collectstatic --noinput; python3 ./manage.py compilemessages)

if [ ! -e /etc/nginx/sites-enabled/sci-web.conf ]; then
	ln -s /etc/nginx/sites-available/sci-web.conf /etc/nginx/sites-enabled/sci-web.conf
fi
if [ -h /etc/nginx/sites-enabled/default ]; then
	rm -f /etc/nginx/sites-enabled/default
fi
if [ ! -e /etc/uwsgi/apps-enabled/sci-web.ini ]; then
	ln -s /etc/uwsgi/apps-available/sci-web.ini /etc/uwsgi/apps-enabled/sci-web.ini
fi

if [ ! -e /etc/nginx/sci-web.crt ]; then
	openssl req -x509 -newkey rsa:2048 -keyout /etc/nginx/sci-web.key -out /etc/nginx/sci-web.crt -days 10000 -nodes -subj "/CN=sci-web"
	chmod 600 /etc/nginx/sci-web.key
	invoke-rc.d nginx restart||true
fi

# clean old pyc files
find /opt/sci-web -type f -iname '*.pyc' -exec rm -f {} \;
invoke-rc.d uwsgi restart||true
invoke-rc.d nginx restart||true
