#!/bin/sh

if [ -e /var/lib/ganeti/rapi/users ]; then
	sed -i "s/scpassword/`cat /var/lib/ganeti/rapi/users|grep scweb|awk '{print $2}'`/" /opt/sci-web/sci_webinterface/settings.py
fi

(cd /opt/sci-web; ./manage.py migrate; ./manage.py collectstatic --noinput)

if [ ! -e /etc/nginx/sites-enabled/sci-web.conf ]; then
	ln -s /etc/nginx/sites-available/sci-web.conf /etc/nginx/sites-enabled/sci-web.conf
fi
if [ ! -e /etc/uwsgi/apps-enabled/sci-web.ini ]; then
	ln -s /etc/uwsgi/apps-available/sci-web.ini /etc/uwsgi/apps-enabled/sci-web.ini
fi

if [ ! -e /etc/nginx/sci-web.crt ]; then
	openssl req -x509 -newkey rsa:2048 -keyout /etc/nginx/sci-web.key -out /etc/nginx/sci-web.crt -days 10000 -nodes -subj "/CN=sci-web"
	chmod 600 /etc/nginx/sci-web.key
	invoke-rc.d nginx restart||true
fi

# clean old pyc files
find /opt/sci-web -type f -iname '*.pyc' -exec rm -f {} \;
invoke-rc.d uwsgi restart||true
